MARBLE-1972 sub items in menus
ndlib/marble-web pull request #137
Opened 2021-12-08 19:39 UTC by danthewolfe

2021-12-17 20:01 UTC, pweikel commented on content/json/menus/help.json
> +          "link": "/project-partners#snite"
Unfortunately, I the "#" is not playing nicely with our links and doesn't resolve to this anchor in the page. Should we just make three separate pages for each partner OR we could just put some jump links on the top of the page and remove the links from the left side menu. Any suggestions here?

2021-12-17 20:05 UTC, pweikel requested changes
See comment in Files Changed

2022-01-12 17:17 UTC, pweikel approved these changes

2022-01-12 18:01 UTC, danthewolfe reviewed
👍

2022-01-12 18:05 UTC, rdoughty approved these changes

2022-01-12 18:08 UTC, merged