Add clickability to profile privacy
ndlib/marble-web pull request #69
Opened 2021-05-26 13:51 UTC by jmille79

MARBLE-1626 Make Access Setting label under portfolio clickable

2021-06-01 14:17 UTC, danthewolfe requested changes
This needs to be rebased on the master branch. 

New code will need to be move from `sites/marble/src/@ndlib/gatsby-theme-marble/components` to `sites/marble/src/components` and imported paths will need updated.

This is in a high churn area that has been temporarily disabled, so it may make sense to wait a bit to merge.

2021-06-04 14:57 UTC, jonhartzler approved these changes

2021-06-04 14:57 UTC, jonhartzler commented on src/@ndlib/gatsby-theme-marble/components/App/Pages/Portfolio/PortfolioBody/Ownership/PrivacyEditSettings/index.js
> +    <React.Fragment>
Small thing but use
<> 
and
</>

2021-06-07 17:50 UTC, danthewolfe approved these changes

2021-06-07 20:39 UTC, merged